# Generated by Django 5.2.4 on 2025-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_email',
            field=models.CharField(max_length=15),
        ),
    ]
