# Generated by Django 5.2.4 on 2025-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_bill_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_email',
            field=models.CharField(max_length=5),
        ),
    ]
